name: als
channels:
  - bioconda
  - defaults
  - conda-forge
dependencies:
  - python=3.7.10
  - r-base>=4.0.0
  - r-essentials
  - r-data.table
  - r-ggplot2
  - r-viridis
  - r-patchwork
  - bioconductor-outrider >=1.6.1
  - r-rmariadb
  - bioconductor-genomicfeatures
  - snakemake==6.2.1
  - pandas==1.2.4
  - pyranges
  - umap-learn
  - matplotlib
  - datashader
  - bokeh
  - holoviews
  - r-umap
  - nb_conda
  - nb_conda_kernels
  - nb_anacondacloud
  - kipoiseq
  - pip:
    - snakemk-util
