name: als
channels:
  - bioconda
  - defaults
  - conda-forge
dependencies:
  - python=3.7.10
  - r-base>=4.0.0
  - r-data.table
  - r-ggplot2
  - bioconductor-outrider >=1.6.1
  - r-rmariadb
  - bioconductor-genomicfeatures
  - snakemake==6.2.1
  - pandas==1.2.4
  - pyranges
  - umap-learn
  - matplotlib
  - datashader
  - bokeh
  - holoviews

