output: data/processed

vcf: /s/raw/als/kaggle/end-als/genomics-data/AnswerALS_subset_annovar.hg38_anno_and_geno.no_intergenic.vcf.gz
gtf: data/common/Homo_sapiens.GRCh38.84.gtf
fasta: /s/genomes/human/hg38/GRCh38.primary_assembly.genome.fa

genome:
  ensembl_release: 84

metadata:
  dir: /s/raw/als/kaggle/end-als/clinical-data/filtered-metadata/metadata/
  participants: /s/raw/als/kaggle/end-als/clinical-data/filtered-metadata/metadata/aals_participants.csv
  released_files: /s/raw/als/kaggle/end-als/clinical-data/filtered-metadata/metadata/aals_released_files.csv

transcriptomics:
  gene_count_dir: /s/raw/als/kaggle/end-als/transcriptomics-data/L3_counts/

mmsplice:
  results: data/processed/mmsplice_exon/results.csv
  
outrider:
  fpkm_cutoff: 1.5
  padj_cutoff: 0.05
  counts: data/processed/outrider/gene_counts.tsv
  results: data/processed/outrider/results_old.tsv

ppi:
  gene_seed_prob: data/processed/networkanalysis/prob_of_reaching_gene_from_seeds.tsv

genes_gtf: data/processed/outrider/outlier_gene_gtf.csv

literature:
  nature_review: data/processed/literature/nature_review_als_genes.csv
  wgs: data/processed/literature/wgs_als_genes.csv

variants:
  vep: /s/project/kaggle-als/vep_annotations/ensembl_bychr.parquet/chrom={chrom}/
  prioritized_chrom:  data/processed/variants/prioritized_variants_chrom={chrom}.csv
  prioritized:  data/processed/variants/prioritized_variants.csv
  results_prioritized: data/processed/results_prioritized_variants.csv
