output: data/processed
figures: reports/figures

plots: true  # whether to inlude plotting rules in dependency graph

vcf: /s/raw/als/kaggle/end-als/genomics-data/AnswerALS_subset_annovar.hg38_anno_and_geno.no_intergenic.vcf.gz
gtf: data/common/Homo_sapiens.GRCh38.84.gtf
fasta: /s/genomes/human/hg38/GRCh38.primary_assembly.genome.fa

genome:
  ensembl_release: 84
  
metadata:
  dir: /s/raw/als/kaggle/end-als/clinical-data/filtered-metadata/metadata/
  participants: /s/raw/als/kaggle/end-als/clinical-data/filtered-metadata/metadata/aals_participants.csv
  dataportal: /s/raw/als/kaggle/end-als/clinical-data/filtered-metadata/metadata/aals_dataportal_datatable.csv
  released_files: /s/raw/als/kaggle/end-als/clinical-data/filtered-metadata/metadata/aals_released_files.csv

annotation_cols:
  - Sex
  # - Batch_ID
  - Revised_El_Escorial_Criteria
  - Site_of_Onset
  - Primary_Tissue
  - Case_Control
  - Race
  - Age

transcriptomics:
  gene_count_dir: /s/raw/als/kaggle/end-als/transcriptomics-data/L3_counts/

mmsplice:
  results: data/processed/mmsplice_exon/results.csv
  
outrider:
  fpkm_cutoff: 1.5
  padj_cutoff: 0.05
  counts: data/processed/outrider/gene_counts.tsv
  results: data/processed/outrider/results.tsv

ppi:
  gene_seed_prob: data/processed/network_analysis/prob_of_reaching_gene_from_seeds.tsv

genes_gtf: data/processed/outrider/outlier_gene_gtf.csv

literature:
  nature_review: data/processed/literature/nature_review_als_genes.csv
  wgs: data/processed/literature/wgs_als_genes.csv
  alsod: data/processed/literature/alsod.csv

vep:
  human_genome_version: "hg38"
  assembly: "GRCh38"
  vep_cache: "/opt/modules/i12g/conda-ensembl-vep/99/cachedir"
  loftee_data_dir: "/s/raw/loftee/{ASSEMBLY}"
  cadd_dir: "/s/raw/cadd/v1.6/{ASSEMBLY}"
  gnomad_vcf: "/s/raw/gnomad/2.1.1/{HUMAN_GENOME_VERSION}/gnomad.genomes.r2.1.1.sites.vcf.gz"

variants:
  vep: /s/project/kaggle-als/vep_annotations/ensembl_bychr.parquet/chrom={chrom}/
  vep_pq: /s/project/kaggle-als/vep_annotations/ensembl_bychr.parquet/
  prioritized_chrom:  data/processed/variants/prioritized_variants_chrom={chrom}.csv
  prioritized: data/processed/variants/prioritized_variants.csv

results_all: data/processed/results_all.csv
results_prioritized: data/processed/results_prioritized_variants.csv
