output: data/processed
figures: reports/figures

plots: true  # whether to inlude plotting rules in dependency graph

vcf: data/raw/genomics-data/AnswerALS_subset_annovar.hg38_anno_and_geno.no_intergenic.vcf.gz
gtf: data/external/hg38/Homo_sapiens.GRCh38.84.gtf
fasta: data/external/hg38/GRCh38.primary_assembly.genome.fa

genome:
  ensembl_release: 84
  
metadata:
  dir: data/raw/clinical-data/filtered-metadata/metadata/
  participants: data/raw/clinical-data/filtered-metadata/metadata/aals_participants.csv
  dataportal: data/raw/clinical-data/filtered-metadata/metadata/aals_dataportal_datatable.csv
  released_files: data/raw/clinical-data/filtered-metadata/metadata/aals_released_files.csv

annotation_cols:
  - Sex
  # - Batch_ID
  - Revised_El_Escorial_Criteria
  - Site_of_Onset
  - Primary_Tissue
  - Case_Control
  - Race
  #- Age_At_Symptom_Onset

transcriptomics:
  gene_count_dir: data/raw/transcriptomics-data/L3_counts/

mmsplice:
  results: data/processed/mmsplice_exon/results.csv
  
outrider:
  fpkm_cutoff: 1.5
  padj_cutoff: 0.05
  counts: data/processed/outrider/gene_counts.tsv
  results: data/processed/outrider/results.tsv

ppi:
  string_url: https://stringdb-static.org/download/protein.links.detailed.v11.0/9606.protein.links.detailed.v11.0.txt.gz
  gene_seed_prob: data/processed/network_analysis/prob_of_reaching_gene_from_seeds.tsv

genes_gtf: data/processed/outrider/outlier_gene_gtf.csv

literature:
  nature_review: data/processed/literature/nature_review_als_genes.csv
  nature_review_with_ensg: data/external/nature_review_als_genes_ensg.csv
  wgs: data/processed/literature/wgs_als_genes.csv
  alsod: data/processed/literature/alsod.csv

vep:
  human_genome_version: hg38
  assembly: GRCh38
  vep_cache: data/intermediate/ensembl_cache
  loftee_data_dir: data/external/vep/loftee/{ASSEMBLY}
  cadd_dir: data/external/vep/cadd/v1.6/{ASSEMBLY}
  gnomad_vcf: data/external/gnomad/2.1.1/{HUMAN_GENOME_VERSION}/gnomad.genomes.r2.1.1.sites.vcf.gz

variants:
  vep: data/processed/vep_annotations/ensembl_bychr.parquet/chrom={chrom}/
  vep_pq: data/processed/vep_annotations/ensembl_bychr.parquet/
  prioritized_chrom:  data/processed/variants/prioritized_variants_chrom={chrom}.csv
  prioritized: data/processed/variants/prioritized_variants.csv

results_all: data/processed/results_all.csv
results_prioritized: data/processed/results_prioritized_variants.csv
