vcf: /s/raw/als/kaggle/end-als/genomics-data/AnswerALS_subset_annovar.hg38_anno_and_geno.no_intergenic.vcf
metadata:
  dir: /s/raw/als/kaggle/end-als/clinical-data/filtered-metadata/metadata/
  participants: /s/raw/als/kaggle/end-als/clinical-data/filtered-metadata/metadata/aals_participants.csv
transcriptomics:
  gene_count_dir: /s/raw/als/kaggle/end-als/transcriptomics-data/L3_counts/

outrider:
  counts: data/processed/outrider/gene_counts.tsv
  results: data/processed/outrider/results.tsv
